services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - ./server/.env:/app/.env
  client:
      container_name: client
      build:
        context: ./client
        dockerfile: Dockerfile
      ports: 
        - "3000:3000"
      volumes:
        - ./client/.env:/app/.env